// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/budget.dart';
import 'data/models/debt.dart';
import 'data/models/expense.dart';
import 'data/models/goal.dart';
import 'data/models/income.dart';
import 'data/models/payment.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8227614500184432177),
    name: 'Expense',
    lastPropertyId: const obx_int.IdUid(9, 2653738939167739630),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8015626204576400402),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7017813908622501221),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4805299823323995966),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8142812335250277598),
        name: 'isPaid',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 430998323156520673),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 20779302750942761),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6704499808924743924),
        name: 'dbCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2609850132850262329),
        name: 'dbCurrency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2653738939167739630),
        name: 'colorHex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8936614305943007624),
    name: 'Income',
    lastPropertyId: const obx_int.IdUid(9, 3465681778592085081),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 75975641029195876),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4421862611846571110),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3893024187284622433),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8745196722495636425),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 122837625025693736),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4061348752870051198),
        name: 'colorHex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3946931914171757653),
        name: 'dbCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8867492958513053605),
        name: 'dbCurrency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3465681778592085081),
        name: 'dbRecurrence',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8398376945150350058),
    name: 'Goal',
    lastPropertyId: const obx_int.IdUid(8, 8215597851823042866),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2007294672207836982),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3762366000080070559),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4984594604991342198),
        name: 'targetAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6927531384279737354),
        name: 'currentAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2539819045219799441),
        name: 'startDateMilli',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5005623492141411832),
        name: 'deadlineMilli',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7546841991390953769),
        name: 'categoryIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8215597851823042866),
        name: 'dbCurrency',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7502451798277903778),
    name: 'Debt',
    lastPropertyId: const obx_int.IdUid(10, 2474889688355389263),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5970035092619372742),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4601289411960708624),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2187728559232038313),
        name: 'creditor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6091375292116588284),
        name: 'totalAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6191293605324194103),
        name: 'remainingAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 113487511494024140),
        name: 'interestRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8700492353083817079),
        name: 'dueDateMilli',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7581570750914452252),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4084936473241046134),
        name: 'dbCurrency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2474889688355389263),
        name: 'minimumPayment',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'payments',
        srcEntity: 'Payment',
        srcField: 'debt',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 4425572893543727994),
    name: 'Payment',
    lastPropertyId: const obx_int.IdUid(5, 6477457538515216353),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7703682160376137992),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 514891938525210185),
        name: 'amountPaid',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5671098793648555514),
        name: 'paymentDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8004230338219543986),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6477457538515216353),
        name: 'debtId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 1801596210573471784),
        relationField: 'debt',
        relationTarget: 'Debt',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 9049747817326412775),
    name: 'Budget',
    lastPropertyId: const obx_int.IdUid(6, 2574199423382725367),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7231066404197682071),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3577178831266225775),
        name: 'limitAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3743437277280066327),
        name: 'dbCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9030009940380572787),
        name: 'targetMonth',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8942974915669833457),
        name: 'notified80',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2574199423382725367),
        name: 'notified100',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 9049747817326412775),
    lastIndexId: const obx_int.IdUid(1, 1801596210573471784),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Expense: obx_int.EntityDefinition<Expense>(
      model: _entities[0],
      toOneRelations: (Expense object) => [],
      toManyRelations: (Expense object) => {},
      getId: (Expense object) => object.id,
      setId: (Expense object, int id) {
        object.id = id;
      },
      objectToFB: (Expense object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final dbCategoryOffset = fbb.writeString(object.dbCategory);
        final dbCurrencyOffset = fbb.writeString(object.dbCurrency);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addBool(3, object.isPaid);
        fbb.addInt64(4, object.date.millisecondsSinceEpoch);
        fbb.addOffset(5, notesOffset);
        fbb.addOffset(6, dbCategoryOffset);
        fbb.addOffset(7, dbCurrencyOffset);
        fbb.addInt64(8, object.colorHex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final isPaidParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final dbCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final dbCurrencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final colorHexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = Expense(
          id: idParam,
          name: nameParam,
          amount: amountParam,
          isPaid: isPaidParam,
          date: dateParam,
          dbCategory: dbCategoryParam,
          dbCurrency: dbCurrencyParam,
          notes: notesParam,
          colorHex: colorHexParam,
        );

        return object;
      },
    ),
    Income: obx_int.EntityDefinition<Income>(
      model: _entities[1],
      toOneRelations: (Income object) => [],
      toManyRelations: (Income object) => {},
      getId: (Income object) => object.id,
      setId: (Income object, int id) {
        object.id = id;
      },
      objectToFB: (Income object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final dbCategoryOffset = fbb.writeString(object.dbCategory);
        final dbCurrencyOffset = fbb.writeString(object.dbCurrency);
        final dbRecurrenceOffset = fbb.writeString(object.dbRecurrence);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addOffset(4, notesOffset);
        fbb.addInt64(5, object.colorHex);
        fbb.addOffset(6, dbCategoryOffset);
        fbb.addOffset(7, dbCurrencyOffset);
        fbb.addOffset(8, dbRecurrenceOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final colorHexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final dbCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final dbCurrencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final dbRecurrenceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = Income(
          id: idParam,
          name: nameParam,
          amount: amountParam,
          date: dateParam,
          colorHex: colorHexParam,
          dbCategory: dbCategoryParam,
          dbCurrency: dbCurrencyParam,
          dbRecurrence: dbRecurrenceParam,
          notes: notesParam,
        );

        return object;
      },
    ),
    Goal: obx_int.EntityDefinition<Goal>(
      model: _entities[2],
      toOneRelations: (Goal object) => [],
      toManyRelations: (Goal object) => {},
      getId: (Goal object) => object.id,
      setId: (Goal object, int id) {
        object.id = id;
      },
      objectToFB: (Goal object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final dbCurrencyOffset = fbb.writeString(object.dbCurrency);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.targetAmount);
        fbb.addFloat64(3, object.currentAmount);
        fbb.addInt64(4, object.startDateMilli);
        fbb.addInt64(5, object.deadlineMilli);
        fbb.addInt64(6, object.categoryIndex);
        fbb.addOffset(7, dbCurrencyOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final targetAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final currentAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final startDateMilliParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final deadlineMilliParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final categoryIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final dbCurrencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = Goal(
          id: idParam,
          name: nameParam,
          targetAmount: targetAmountParam,
          currentAmount: currentAmountParam,
          startDateMilli: startDateMilliParam,
          deadlineMilli: deadlineMilliParam,
          categoryIndex: categoryIndexParam,
          dbCurrency: dbCurrencyParam,
        );

        return object;
      },
    ),
    Debt: obx_int.EntityDefinition<Debt>(
      model: _entities[3],
      toOneRelations: (Debt object) => [],
      toManyRelations: (Debt object) => {
        obx_int.RelInfo<Payment>.toOneBacklink(
          5,
          object.id,
          (Payment srcObject) => srcObject.debt,
        ): object.payments,
      },
      getId: (Debt object) => object.id,
      setId: (Debt object, int id) {
        object.id = id;
      },
      objectToFB: (Debt object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final creditorOffset = fbb.writeString(object.creditor);
        final dbCurrencyOffset = fbb.writeString(object.dbCurrency);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, creditorOffset);
        fbb.addFloat64(3, object.totalAmount);
        fbb.addFloat64(4, object.remainingAmount);
        fbb.addFloat64(5, object.interestRate);
        fbb.addInt64(6, object.dueDateMilli);
        fbb.addInt64(7, object.typeIndex);
        fbb.addOffset(8, dbCurrencyOffset);
        fbb.addFloat64(9, object.minimumPayment);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final creditorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final totalAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final remainingAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final interestRateParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final dueDateMilliParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final dbCurrencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final minimumPaymentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final object = Debt(
          id: idParam,
          title: titleParam,
          creditor: creditorParam,
          totalAmount: totalAmountParam,
          remainingAmount: remainingAmountParam,
          interestRate: interestRateParam,
          dueDateMilli: dueDateMilliParam,
          typeIndex: typeIndexParam,
          dbCurrency: dbCurrencyParam,
          minimumPayment: minimumPaymentParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Debt>(
          object.payments,
          store,
          obx_int.RelInfo<Payment>.toOneBacklink(
            5,
            object.id,
            (Payment srcObject) => srcObject.debt,
          ),
        );
        return object;
      },
    ),
    Payment: obx_int.EntityDefinition<Payment>(
      model: _entities[4],
      toOneRelations: (Payment object) => [object.debt],
      toManyRelations: (Payment object) => {},
      getId: (Payment object) => object.id,
      setId: (Payment object, int id) {
        object.id = id;
      },
      objectToFB: (Payment object, fb.Builder fbb) {
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.amountPaid);
        fbb.addInt64(2, object.paymentDate.millisecondsSinceEpoch);
        fbb.addOffset(3, notesOffset);
        fbb.addInt64(4, object.debt.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final amountPaidParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final paymentDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = Payment(
          id: idParam,
          amountPaid: amountPaidParam,
          paymentDate: paymentDateParam,
          notes: notesParam,
        );
        object.debt.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.debt.attach(store);
        return object;
      },
    ),
    Budget: obx_int.EntityDefinition<Budget>(
      model: _entities[5],
      toOneRelations: (Budget object) => [],
      toManyRelations: (Budget object) => {},
      getId: (Budget object) => object.id,
      setId: (Budget object, int id) {
        object.id = id;
      },
      objectToFB: (Budget object, fb.Builder fbb) {
        final dbCategoryOffset = fbb.writeString(object.dbCategory);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.limitAmount);
        fbb.addOffset(2, dbCategoryOffset);
        fbb.addInt64(3, object.targetMonth.millisecondsSinceEpoch);
        fbb.addBool(4, object.notified80);
        fbb.addBool(5, object.notified100);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final limitAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final dbCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final targetMonthParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final notified80Param = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final notified100Param = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = Budget(
          id: idParam,
          limitAmount: limitAmountParam,
          dbCategory: dbCategoryParam,
          targetMonth: targetMonthParam,
          notified80: notified80Param,
          notified100: notified100Param,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Expense] entity fields to define ObjectBox queries.
class Expense_ {
  /// See [Expense.id].
  static final id = obx.QueryIntegerProperty<Expense>(
    _entities[0].properties[0],
  );

  /// See [Expense.name].
  static final name = obx.QueryStringProperty<Expense>(
    _entities[0].properties[1],
  );

  /// See [Expense.amount].
  static final amount = obx.QueryDoubleProperty<Expense>(
    _entities[0].properties[2],
  );

  /// See [Expense.isPaid].
  static final isPaid = obx.QueryBooleanProperty<Expense>(
    _entities[0].properties[3],
  );

  /// See [Expense.date].
  static final date = obx.QueryDateProperty<Expense>(
    _entities[0].properties[4],
  );

  /// See [Expense.notes].
  static final notes = obx.QueryStringProperty<Expense>(
    _entities[0].properties[5],
  );

  /// See [Expense.dbCategory].
  static final dbCategory = obx.QueryStringProperty<Expense>(
    _entities[0].properties[6],
  );

  /// See [Expense.dbCurrency].
  static final dbCurrency = obx.QueryStringProperty<Expense>(
    _entities[0].properties[7],
  );

  /// See [Expense.colorHex].
  static final colorHex = obx.QueryIntegerProperty<Expense>(
    _entities[0].properties[8],
  );
}

/// [Income] entity fields to define ObjectBox queries.
class Income_ {
  /// See [Income.id].
  static final id = obx.QueryIntegerProperty<Income>(
    _entities[1].properties[0],
  );

  /// See [Income.name].
  static final name = obx.QueryStringProperty<Income>(
    _entities[1].properties[1],
  );

  /// See [Income.amount].
  static final amount = obx.QueryDoubleProperty<Income>(
    _entities[1].properties[2],
  );

  /// See [Income.date].
  static final date = obx.QueryDateProperty<Income>(_entities[1].properties[3]);

  /// See [Income.notes].
  static final notes = obx.QueryStringProperty<Income>(
    _entities[1].properties[4],
  );

  /// See [Income.colorHex].
  static final colorHex = obx.QueryIntegerProperty<Income>(
    _entities[1].properties[5],
  );

  /// See [Income.dbCategory].
  static final dbCategory = obx.QueryStringProperty<Income>(
    _entities[1].properties[6],
  );

  /// See [Income.dbCurrency].
  static final dbCurrency = obx.QueryStringProperty<Income>(
    _entities[1].properties[7],
  );

  /// See [Income.dbRecurrence].
  static final dbRecurrence = obx.QueryStringProperty<Income>(
    _entities[1].properties[8],
  );
}

/// [Goal] entity fields to define ObjectBox queries.
class Goal_ {
  /// See [Goal.id].
  static final id = obx.QueryIntegerProperty<Goal>(_entities[2].properties[0]);

  /// See [Goal.name].
  static final name = obx.QueryStringProperty<Goal>(_entities[2].properties[1]);

  /// See [Goal.targetAmount].
  static final targetAmount = obx.QueryDoubleProperty<Goal>(
    _entities[2].properties[2],
  );

  /// See [Goal.currentAmount].
  static final currentAmount = obx.QueryDoubleProperty<Goal>(
    _entities[2].properties[3],
  );

  /// See [Goal.startDateMilli].
  static final startDateMilli = obx.QueryIntegerProperty<Goal>(
    _entities[2].properties[4],
  );

  /// See [Goal.deadlineMilli].
  static final deadlineMilli = obx.QueryIntegerProperty<Goal>(
    _entities[2].properties[5],
  );

  /// See [Goal.categoryIndex].
  static final categoryIndex = obx.QueryIntegerProperty<Goal>(
    _entities[2].properties[6],
  );

  /// See [Goal.dbCurrency].
  static final dbCurrency = obx.QueryStringProperty<Goal>(
    _entities[2].properties[7],
  );
}

/// [Debt] entity fields to define ObjectBox queries.
class Debt_ {
  /// See [Debt.id].
  static final id = obx.QueryIntegerProperty<Debt>(_entities[3].properties[0]);

  /// See [Debt.title].
  static final title = obx.QueryStringProperty<Debt>(
    _entities[3].properties[1],
  );

  /// See [Debt.creditor].
  static final creditor = obx.QueryStringProperty<Debt>(
    _entities[3].properties[2],
  );

  /// See [Debt.totalAmount].
  static final totalAmount = obx.QueryDoubleProperty<Debt>(
    _entities[3].properties[3],
  );

  /// See [Debt.remainingAmount].
  static final remainingAmount = obx.QueryDoubleProperty<Debt>(
    _entities[3].properties[4],
  );

  /// See [Debt.interestRate].
  static final interestRate = obx.QueryDoubleProperty<Debt>(
    _entities[3].properties[5],
  );

  /// See [Debt.dueDateMilli].
  static final dueDateMilli = obx.QueryIntegerProperty<Debt>(
    _entities[3].properties[6],
  );

  /// See [Debt.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<Debt>(
    _entities[3].properties[7],
  );

  /// See [Debt.dbCurrency].
  static final dbCurrency = obx.QueryStringProperty<Debt>(
    _entities[3].properties[8],
  );

  /// See [Debt.minimumPayment].
  static final minimumPayment = obx.QueryDoubleProperty<Debt>(
    _entities[3].properties[9],
  );

  /// see [Debt.payments]
  static final payments = obx.QueryBacklinkToMany<Payment, Debt>(Payment_.debt);
}

/// [Payment] entity fields to define ObjectBox queries.
class Payment_ {
  /// See [Payment.id].
  static final id = obx.QueryIntegerProperty<Payment>(
    _entities[4].properties[0],
  );

  /// See [Payment.amountPaid].
  static final amountPaid = obx.QueryDoubleProperty<Payment>(
    _entities[4].properties[1],
  );

  /// See [Payment.paymentDate].
  static final paymentDate = obx.QueryDateProperty<Payment>(
    _entities[4].properties[2],
  );

  /// See [Payment.notes].
  static final notes = obx.QueryStringProperty<Payment>(
    _entities[4].properties[3],
  );

  /// See [Payment.debt].
  static final debt = obx.QueryRelationToOne<Payment, Debt>(
    _entities[4].properties[4],
  );
}

/// [Budget] entity fields to define ObjectBox queries.
class Budget_ {
  /// See [Budget.id].
  static final id = obx.QueryIntegerProperty<Budget>(
    _entities[5].properties[0],
  );

  /// See [Budget.limitAmount].
  static final limitAmount = obx.QueryDoubleProperty<Budget>(
    _entities[5].properties[1],
  );

  /// See [Budget.dbCategory].
  static final dbCategory = obx.QueryStringProperty<Budget>(
    _entities[5].properties[2],
  );

  /// See [Budget.targetMonth].
  static final targetMonth = obx.QueryDateProperty<Budget>(
    _entities[5].properties[3],
  );

  /// See [Budget.notified80].
  static final notified80 = obx.QueryBooleanProperty<Budget>(
    _entities[5].properties[4],
  );

  /// See [Budget.notified100].
  static final notified100 = obx.QueryBooleanProperty<Budget>(
    _entities[5].properties[5],
  );
}
